version: '2.1'

services:
  salt-master:
    image: mirceaulinic/salt-master:2017.7.5
    hostname: salt-master
    container_name: salt-master
    environment:
      - LOG_LEVEL
    volumes:
      - ./master:/etc/salt/master
      - ./pillar/:/etc/salt/pillar/
      - ./states/:/etc/salt/states/
      - ${HOME}/salt/:/usr/lib/python2.7/dist-packages/salt/
      - ${HOME}/salt/:/usr/lib/python3.5/dist-packages/salt/
  salt-proxy:
    image: mirceaulinic/salt-proxy:2017.7.5
    hostname: ${PROXYID}
    container_name: salt-proxy-${PROXYID}
    volumes:
      - ./proxy:/etc/salt/proxy
      - ${HOME}/salt/:/usr/lib/python2.7/dist-packages/salt/
      - ${HOME}/salt/:/usr/lib/python3.5/dist-packages/salt/
    environment:
      - LOG_LEVEL
      - PROXYID
    depends_on:
      - salt-master
